### ISSUE TITLE
Change module install to CurrentUser

### ISSUE THREAD

**Issue by salty2011** [ProfKaz/MicrosoftPurviewTools#1]
Reading through the script you have a section to check if the session is elevated before attempting to install the required modules.

See: https://github.com/ProfKaz/MicrosoftPurviewTools/blob/9904f5a450486a1c19ac9b50e2f7b34f4b7e1c05/Information%20Protection/Script/MSPurviewIPCollector.ps1#L144

However it would be better to perform the installation in the current user context instead of elevating to a privileged terminal session. This can be done by change the the install command as follows

`Install-Module $module -Scope CurrentUser -ErrorAction Stop`

This would now perform the installation of the module in the user scope. This is also better from a portability and security standpoint as some organisations do not allow for elevation to Local Admin.

**Comment by ProfKaz** [comment]
Thanks for the feedback, I´ll consider that in the next version.
